version: '3.8'

services:
  task_management:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm 
    ports:
      - "8080:8080" 
    depends_on:
      - db
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/task_management
      - QUARKUS_DATASOURCE_USERNAME=<youruser>
      - QUARKUS_DATASOURCE_PASSWORD=<yourpassword>
      - JAVA_OPTS=-Xmx512m 
    networks:
      - mynetwork

  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task_management
      POSTGRES_USER: <youruser>
      POSTGRES_PASSWORD: <yourpassword>
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
